///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Colecciones_Biologia
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Colecciones_BiologiaRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ab6f0686-5f78-49af-81c1-274fbf04a566")]
    public partial class Colecciones_BiologiaRepository : RepoGenBaseFolder
    {
        static Colecciones_BiologiaRepository instance = new Colecciones_BiologiaRepository();
        Colecciones_BiologiaRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        Colecciones_BiologiaRepositoryFolders.GettingStartedWithRanorexStudioRaAppFolder _gettingstartedwithranorexstudiora;
        Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVGMozillaFirefoxAppFolder _coleccionbiologiauvgmozillafirefox;
        Colecciones_BiologiaRepositoryFolders.FirefoxAppFolder _firefox;
        Colecciones_BiologiaRepositoryFolders.Form21WhatsAppMozillaFirefoxAppFolder _form21whatsappmozillafirefox;
        Colecciones_BiologiaRepositoryFolders.LiteappsMcafeeComAppFolder _liteappsmcafeecom;

        /// <summary>
        /// Gets the singleton class instance representing the Colecciones_BiologiaRepository element repository.
        /// </summary>
        [RepositoryFolder("ab6f0686-5f78-49af-81c1-274fbf04a566")]
        public static Colecciones_BiologiaRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Colecciones_BiologiaRepository() 
            : base("Colecciones_BiologiaRepository", "/", null, 0, false, "ab6f0686-5f78-49af-81c1-274fbf04a566", ".\\RepositoryImages\\Colecciones_BiologiaRepositoryab6f0686.rximgres")
        {
            _applicationundertest = new Colecciones_BiologiaRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _gettingstartedwithranorexstudiora = new Colecciones_BiologiaRepositoryFolders.GettingStartedWithRanorexStudioRaAppFolder(this);
            _coleccionbiologiauvgmozillafirefox = new Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVGMozillaFirefoxAppFolder(this);
            _firefox = new Colecciones_BiologiaRepositoryFolders.FirefoxAppFolder(this);
            _form21whatsappmozillafirefox = new Colecciones_BiologiaRepositoryFolders.Form21WhatsAppMozillaFirefoxAppFolder(this);
            _liteappsmcafeecom = new Colecciones_BiologiaRepositoryFolders.LiteappsMcafeeComAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ab6f0686-5f78-49af-81c1-274fbf04a566")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("70f05b26-bb53-443f-8e3a-5276425e6868")]
        public virtual Colecciones_BiologiaRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The GettingStartedWithRanorexStudioRa folder.
        /// </summary>
        [RepositoryFolder("44181718-fae2-4a1c-b44c-0dcfe0f85f18")]
        public virtual Colecciones_BiologiaRepositoryFolders.GettingStartedWithRanorexStudioRaAppFolder GettingStartedWithRanorexStudioRa
        {
            get { return _gettingstartedwithranorexstudiora; }
        }

        /// <summary>
        /// The ColeccionBiologiaUVGMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("c6bb8a0a-3b97-4387-a56f-2d6674a5f1ca")]
        public virtual Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVGMozillaFirefoxAppFolder ColeccionBiologiaUVGMozillaFirefox
        {
            get { return _coleccionbiologiauvgmozillafirefox; }
        }

        /// <summary>
        /// The Firefox folder.
        /// </summary>
        [RepositoryFolder("9cc3bb7f-c2cf-455b-b2e1-1d15b4ddbaba")]
        public virtual Colecciones_BiologiaRepositoryFolders.FirefoxAppFolder Firefox
        {
            get { return _firefox; }
        }

        /// <summary>
        /// The Form21WhatsAppMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("161da3d2-941e-402a-aeca-10b83e17b8b0")]
        public virtual Colecciones_BiologiaRepositoryFolders.Form21WhatsAppMozillaFirefoxAppFolder Form21WhatsAppMozillaFirefox
        {
            get { return _form21whatsappmozillafirefox; }
        }

        /// <summary>
        /// The LiteappsMcafeeCom folder.
        /// </summary>
        [RepositoryFolder("e825de0e-7071-46c9-9632-c746bfca97b7")]
        public virtual Colecciones_BiologiaRepositoryFolders.LiteappsMcafeeComAppFolder LiteappsMcafeeCom
        {
            get { return _liteappsmcafeecom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Colecciones_BiologiaRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("70f05b26-bb53-443f-8e3a-5276425e6868")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='localhost:3000']", parentFolder, 30000, null, false, "70f05b26-bb53-443f-8e3a-5276425e6868", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("70f05b26-bb53-443f-8e3a-5276425e6868")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("70f05b26-bb53-443f-8e3a-5276425e6868")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The GettingStartedWithRanorexStudioRaAppFolder folder.
        /// </summary>
        [RepositoryFolder("44181718-fae2-4a1c-b44c-0dcfe0f85f18")]
        public partial class GettingStartedWithRanorexStudioRaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _coleccionbiologiauvgInfo;

            /// <summary>
            /// Creates a new GettingStartedWithRanorexStudioRa  folder.
            /// </summary>
            public GettingStartedWithRanorexStudioRaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GettingStartedWithRanorexStudioRa", "/form[@title>'Getting Started with Ranorex']", parentFolder, 30000, null, true, "44181718-fae2-4a1c-b44c-0dcfe0f85f18", "")
            {
                _coleccionbiologiauvgInfo = new RepoItemInfo(this, "ColeccionBiologiaUVG", "toolbar[@accessiblename='Browser tabs']/?/?/tabpage[@accessiblename='Coleccion Biologia UVG']", 30000, null, "3c0819c7-f4ea-4b6b-822f-c42439645ba3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("44181718-fae2-4a1c-b44c-0dcfe0f85f18")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("44181718-fae2-4a1c-b44c-0dcfe0f85f18")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG item.
            /// </summary>
            [RepositoryItem("3c0819c7-f4ea-4b6b-822f-c42439645ba3")]
            public virtual Ranorex.TabPage ColeccionBiologiaUVG
            {
                get
                {
                    return _coleccionbiologiauvgInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG item info.
            /// </summary>
            [RepositoryItemInfo("3c0819c7-f4ea-4b6b-822f-c42439645ba3")]
            public virtual RepoItemInfo ColeccionBiologiaUVGInfo
            {
                get
                {
                    return _coleccionbiologiauvgInfo;
                }
            }
        }

        /// <summary>
        /// The ColeccionBiologiaUVGMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("c6bb8a0a-3b97-4387-a56f-2d6674a5f1ca")]
        public partial class ColeccionBiologiaUVGMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVGFolder _coleccionbiologiauvg;
            Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVG1Folder _coleccionbiologiauvg1;
            RepoItemInfo _coleccionbiologiauvg2Info;
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new ColeccionBiologiaUVGMozillaFirefox  folder.
            /// </summary>
            public ColeccionBiologiaUVGMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ColeccionBiologiaUVGMozillaFirefox", "/form[@title>'Coleccion Biologia UVG - Mozilla']", parentFolder, 30000, null, true, "c6bb8a0a-3b97-4387-a56f-2d6674a5f1ca", "")
            {
                _coleccionbiologiauvg = new Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVGFolder(this);
                _coleccionbiologiauvg1 = new Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVG1Folder(this);
                _coleccionbiologiauvg2Info = new RepoItemInfo(this, "ColeccionBiologiaUVG2", "toolbar[@accessiblename='Browser tabs']/?/?/tabpage[@accessiblerole='PageTab' and @title='Coleccion Biologia UVG' and @index='0']", 30000, null, "273ddcde-cec8-4f86-9c37-ad976fb847a8");
                _noneInfo = new RepoItemInfo(this, "None", "container[@accessiblerole='Grouping']/?/?/element[@accessiblerole='None']", 30000, null, "d51f10fb-8da5-4abb-a21d-ea6834b87fe2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c6bb8a0a-3b97-4387-a56f-2d6674a5f1ca")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c6bb8a0a-3b97-4387-a56f-2d6674a5f1ca")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG2 item.
            /// </summary>
            [RepositoryItem("273ddcde-cec8-4f86-9c37-ad976fb847a8")]
            public virtual Ranorex.TabPage ColeccionBiologiaUVG2
            {
                get
                {
                    return _coleccionbiologiauvg2Info.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG2 item info.
            /// </summary>
            [RepositoryItemInfo("273ddcde-cec8-4f86-9c37-ad976fb847a8")]
            public virtual RepoItemInfo ColeccionBiologiaUVG2Info
            {
                get
                {
                    return _coleccionbiologiauvg2Info;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("d51f10fb-8da5-4abb-a21d-ea6834b87fe2")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("d51f10fb-8da5-4abb-a21d-ea6834b87fe2")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG folder.
            /// </summary>
            [RepositoryFolder("5c37f68a-3680-4c4f-9fbf-e6c3fd3fb810")]
            public virtual Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVGFolder ColeccionBiologiaUVG
            {
                get { return _coleccionbiologiauvg; }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG1 folder.
            /// </summary>
            [RepositoryFolder("db5e99c1-9021-46aa-a1ec-9479f9a8df9d")]
            public virtual Colecciones_BiologiaRepositoryFolders.ColeccionBiologiaUVG1Folder ColeccionBiologiaUVG1
            {
                get { return _coleccionbiologiauvg1; }
            }
        }

        /// <summary>
        /// The ColeccionBiologiaUVGFolder folder.
        /// </summary>
        [RepositoryFolder("5c37f68a-3680-4c4f-9fbf-e6c3fd3fb810")]
        public partial class ColeccionBiologiaUVGFolder : RepoGenBaseFolder
        {
            RepoItemInfo _homeInfo;
            RepoItemInfo _sobrenosotrosInfo;
            RepoItemInfo _amaziliacandida1Info;
            RepoItemInfo _noneInfo;

            /// <summary>
            /// Creates a new ColeccionBiologiaUVG  folder.
            /// </summary>
            public ColeccionBiologiaUVGFolder(RepoGenBaseFolder parentFolder) :
                    base("ColeccionBiologiaUVG", ".//container[@accessiblename='Coleccion Biologia UVG']", parentFolder, 30000, null, false, "5c37f68a-3680-4c4f-9fbf-e6c3fd3fb810", "")
            {
                _homeInfo = new RepoItemInfo(this, "Home", "?/?/element/list[@accessiblerole='List']/listitem[@accessiblename='Home']/link[@accessiblename='Home']/text[@accessiblename='Home']", 30000, null, "3308826c-9963-4e15-8207-e78607842ebb");
                _sobrenosotrosInfo = new RepoItemInfo(this, "SobreNosotros", "?/?/element/list[@accessiblerole='List']/listitem[@accessiblename='Sobre Nosotros']/link[@accessiblename='Sobre Nosotros']/text[@accessiblename='Sobre Nosotros']", 30000, null, "78877716-3a66-402c-8d23-32d7e9a5649a");
                _amaziliacandida1Info = new RepoItemInfo(this, "AmaziliaCandida1", "element/list[1]/listitem[@accessiblename='Amazilia candida']/text[@accessiblename='Amazilia candida']", 30000, null, "dd7ebbb1-fd2b-4c94-85d1-b908f3f89771");
                _noneInfo = new RepoItemInfo(this, "None", "element/element[2]/element[4]", 30000, null, "93ef2700-7885-4f86-83e3-fd3ce5b8d576");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5c37f68a-3680-4c4f-9fbf-e6c3fd3fb810")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5c37f68a-3680-4c4f-9fbf-e6c3fd3fb810")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("3308826c-9963-4e15-8207-e78607842ebb")]
            public virtual Ranorex.Text Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("3308826c-9963-4e15-8207-e78607842ebb")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The SobreNosotros item.
            /// </summary>
            [RepositoryItem("78877716-3a66-402c-8d23-32d7e9a5649a")]
            public virtual Ranorex.Text SobreNosotros
            {
                get
                {
                    return _sobrenosotrosInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SobreNosotros item info.
            /// </summary>
            [RepositoryItemInfo("78877716-3a66-402c-8d23-32d7e9a5649a")]
            public virtual RepoItemInfo SobreNosotrosInfo
            {
                get
                {
                    return _sobrenosotrosInfo;
                }
            }

            /// <summary>
            /// The AmaziliaCandida1 item.
            /// </summary>
            [RepositoryItem("dd7ebbb1-fd2b-4c94-85d1-b908f3f89771")]
            public virtual Ranorex.Text AmaziliaCandida1
            {
                get
                {
                    return _amaziliacandida1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AmaziliaCandida1 item info.
            /// </summary>
            [RepositoryItemInfo("dd7ebbb1-fd2b-4c94-85d1-b908f3f89771")]
            public virtual RepoItemInfo AmaziliaCandida1Info
            {
                get
                {
                    return _amaziliacandida1Info;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("93ef2700-7885-4f86-83e3-fd3ce5b8d576")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("93ef2700-7885-4f86-83e3-fd3ce5b8d576")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }
        }

        /// <summary>
        /// The ColeccionBiologiaUVG1Folder folder.
        /// </summary>
        [RepositoryFolder("db5e99c1-9021-46aa-a1ec-9479f9a8df9d")]
        public partial class ColeccionBiologiaUVG1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;
            RepoItemInfo _buscarInfo;
            RepoItemInfo _sobrenosotros1Info;
            RepoItemInfo _login1Info;
            RepoItemInfo _textInfo;
            RepoItemInfo _buscar1Info;
            RepoItemInfo _amaziliacandidaInfo;
            RepoItemInfo _noneInfo;
            RepoItemInfo _none1Info;
            RepoItemInfo _departamentoInfo;
            RepoItemInfo _departamento1Info;
            RepoItemInfo _resetInfo;
            RepoItemInfo _localidadpostalcodepostalcodepostalInfo;

            /// <summary>
            /// Creates a new ColeccionBiologiaUVG1  folder.
            /// </summary>
            public ColeccionBiologiaUVG1Folder(RepoGenBaseFolder parentFolder) :
                    base("ColeccionBiologiaUVG1", "container[@accessiblerole='Grouping']//container[@accessiblename='Coleccion Biologia UVG']", parentFolder, 30000, null, false, "db5e99c1-9021-46aa-a1ec-9479f9a8df9d", "")
            {
                _loginInfo = new RepoItemInfo(this, "LogIn", ".//link[@accessiblename='Log in']/button[@accessiblename='Log in']", 30000, null, "8a733a2b-583d-4b2b-8b38-5cf93c4a97b7");
                _buscarInfo = new RepoItemInfo(this, "Buscar", "?/?/text[@accessiblename='Buscar...']", 30000, null, "c0c913cb-7b9e-4e7c-8c9d-20984d20e448");
                _sobrenosotros1Info = new RepoItemInfo(this, "SobreNosotros1", "element/element[1]/list[@accessiblerole='List']/listitem[@accessiblename='Sobre Nosotros']/link[@accessiblename='Sobre Nosotros']", 30000, null, "8e2bcef0-e34f-4002-a805-1951faf4fd4c");
                _login1Info = new RepoItemInfo(this, "Login1", "element/element[3]/button[@accessiblename='Login']", 30000, null, "32ccc02e-b3f5-4132-b81b-495e8b50ee2d");
                _textInfo = new RepoItemInfo(this, "Text", "element/element[3]/text[1]", 30000, null, "4c7a8335-817f-4d71-8c1d-604465fe206a");
                _buscar1Info = new RepoItemInfo(this, "Buscar1", "element/element[3]/text[@accessiblename='Buscar']", 30000, null, "2735d91f-1350-48c3-bcaa-b7f8816613a3");
                _amaziliacandidaInfo = new RepoItemInfo(this, "AmaziliaCandida", "element/list[1]/listitem[@accessiblename='Amazilia candida']", 30000, null, "e8d33f01-8f86-4540-877a-c56906a78ebc");
                _noneInfo = new RepoItemInfo(this, "None", "element[@accessiblerole='None']", 30000, null, "4f2281b1-5419-4a36-b10a-b11a05563b34");
                _none1Info = new RepoItemInfo(this, "None1", "?/?/element[@accessiblerole='None']", 30000, null, "22f9dc48-fce5-4ef3-8433-f6f9fe7e5ab1");
                _departamentoInfo = new RepoItemInfo(this, "Departamento", "element/element[2]/element[4]/button[1]", 30000, null, "e217e966-19cc-4979-ba4d-92fdcf0193ce");
                _departamento1Info = new RepoItemInfo(this, "Departamento1", "element/element[2]/element[4]/button[1]/text[@accessiblename='Departamento']", 30000, null, "7100e9c4-cbe5-4347-b217-4740e02a348a");
                _resetInfo = new RepoItemInfo(this, "Reset", "element/element[2]/element[4]/button[@accessiblename='Reset']", 30000, null, "266de929-25a3-467e-b5c5-6de636a77470");
                _localidadpostalcodepostalcodepostalInfo = new RepoItemInfo(this, "LocalidadPostalCodePostalCodePostal", "element/element[2]/element[4]/text[@accessiblename>'Localidad Postal code Postal']", 30000, null, "d7e7bf43-ed8a-43eb-87a7-2c2156289acb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("db5e99c1-9021-46aa-a1ec-9479f9a8df9d")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("db5e99c1-9021-46aa-a1ec-9479f9a8df9d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn item.
            /// </summary>
            [RepositoryItem("8a733a2b-583d-4b2b-8b38-5cf93c4a97b7")]
            public virtual Ranorex.Button LogIn
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The LogIn item info.
            /// </summary>
            [RepositoryItemInfo("8a733a2b-583d-4b2b-8b38-5cf93c4a97b7")]
            public virtual RepoItemInfo LogInInfo
            {
                get
                {
                    return _loginInfo;
                }
            }

            /// <summary>
            /// The Buscar item.
            /// </summary>
            [RepositoryItem("c0c913cb-7b9e-4e7c-8c9d-20984d20e448")]
            public virtual Ranorex.Text Buscar
            {
                get
                {
                    return _buscarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Buscar item info.
            /// </summary>
            [RepositoryItemInfo("c0c913cb-7b9e-4e7c-8c9d-20984d20e448")]
            public virtual RepoItemInfo BuscarInfo
            {
                get
                {
                    return _buscarInfo;
                }
            }

            /// <summary>
            /// The SobreNosotros1 item.
            /// </summary>
            [RepositoryItem("8e2bcef0-e34f-4002-a805-1951faf4fd4c")]
            public virtual Ranorex.Link SobreNosotros1
            {
                get
                {
                    return _sobrenosotros1Info.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The SobreNosotros1 item info.
            /// </summary>
            [RepositoryItemInfo("8e2bcef0-e34f-4002-a805-1951faf4fd4c")]
            public virtual RepoItemInfo SobreNosotros1Info
            {
                get
                {
                    return _sobrenosotros1Info;
                }
            }

            /// <summary>
            /// The Login1 item.
            /// </summary>
            [RepositoryItem("32ccc02e-b3f5-4132-b81b-495e8b50ee2d")]
            public virtual Ranorex.Button Login1
            {
                get
                {
                    return _login1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Login1 item info.
            /// </summary>
            [RepositoryItemInfo("32ccc02e-b3f5-4132-b81b-495e8b50ee2d")]
            public virtual RepoItemInfo Login1Info
            {
                get
                {
                    return _login1Info;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("4c7a8335-817f-4d71-8c1d-604465fe206a")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("4c7a8335-817f-4d71-8c1d-604465fe206a")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Buscar1 item.
            /// </summary>
            [RepositoryItem("2735d91f-1350-48c3-bcaa-b7f8816613a3")]
            public virtual Ranorex.Text Buscar1
            {
                get
                {
                    return _buscar1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Buscar1 item info.
            /// </summary>
            [RepositoryItemInfo("2735d91f-1350-48c3-bcaa-b7f8816613a3")]
            public virtual RepoItemInfo Buscar1Info
            {
                get
                {
                    return _buscar1Info;
                }
            }

            /// <summary>
            /// The AmaziliaCandida item.
            /// </summary>
            [RepositoryItem("e8d33f01-8f86-4540-877a-c56906a78ebc")]
            public virtual Ranorex.ListItem AmaziliaCandida
            {
                get
                {
                    return _amaziliacandidaInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The AmaziliaCandida item info.
            /// </summary>
            [RepositoryItemInfo("e8d33f01-8f86-4540-877a-c56906a78ebc")]
            public virtual RepoItemInfo AmaziliaCandidaInfo
            {
                get
                {
                    return _amaziliacandidaInfo;
                }
            }

            /// <summary>
            /// The None item.
            /// </summary>
            [RepositoryItem("4f2281b1-5419-4a36-b10a-b11a05563b34")]
            public virtual Ranorex.Unknown None
            {
                get
                {
                    return _noneInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None item info.
            /// </summary>
            [RepositoryItemInfo("4f2281b1-5419-4a36-b10a-b11a05563b34")]
            public virtual RepoItemInfo NoneInfo
            {
                get
                {
                    return _noneInfo;
                }
            }

            /// <summary>
            /// The None1 item.
            /// </summary>
            [RepositoryItem("22f9dc48-fce5-4ef3-8433-f6f9fe7e5ab1")]
            public virtual Ranorex.Unknown None1
            {
                get
                {
                    return _none1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The None1 item info.
            /// </summary>
            [RepositoryItemInfo("22f9dc48-fce5-4ef3-8433-f6f9fe7e5ab1")]
            public virtual RepoItemInfo None1Info
            {
                get
                {
                    return _none1Info;
                }
            }

            /// <summary>
            /// The Departamento item.
            /// </summary>
            [RepositoryItem("e217e966-19cc-4979-ba4d-92fdcf0193ce")]
            public virtual Ranorex.Button Departamento
            {
                get
                {
                    return _departamentoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Departamento item info.
            /// </summary>
            [RepositoryItemInfo("e217e966-19cc-4979-ba4d-92fdcf0193ce")]
            public virtual RepoItemInfo DepartamentoInfo
            {
                get
                {
                    return _departamentoInfo;
                }
            }

            /// <summary>
            /// The Departamento1 item.
            /// </summary>
            [RepositoryItem("7100e9c4-cbe5-4347-b217-4740e02a348a")]
            public virtual Ranorex.Text Departamento1
            {
                get
                {
                    return _departamento1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Departamento1 item info.
            /// </summary>
            [RepositoryItemInfo("7100e9c4-cbe5-4347-b217-4740e02a348a")]
            public virtual RepoItemInfo Departamento1Info
            {
                get
                {
                    return _departamento1Info;
                }
            }

            /// <summary>
            /// The Reset item.
            /// </summary>
            [RepositoryItem("266de929-25a3-467e-b5c5-6de636a77470")]
            public virtual Ranorex.Button Reset
            {
                get
                {
                    return _resetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Reset item info.
            /// </summary>
            [RepositoryItemInfo("266de929-25a3-467e-b5c5-6de636a77470")]
            public virtual RepoItemInfo ResetInfo
            {
                get
                {
                    return _resetInfo;
                }
            }

            /// <summary>
            /// The LocalidadPostalCodePostalCodePostal item.
            /// </summary>
            [RepositoryItem("d7e7bf43-ed8a-43eb-87a7-2c2156289acb")]
            public virtual Ranorex.Text LocalidadPostalCodePostalCodePostal
            {
                get
                {
                    return _localidadpostalcodepostalcodepostalInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LocalidadPostalCodePostalCodePostal item info.
            /// </summary>
            [RepositoryItemInfo("d7e7bf43-ed8a-43eb-87a7-2c2156289acb")]
            public virtual RepoItemInfo LocalidadPostalCodePostalCodePostalInfo
            {
                get
                {
                    return _localidadpostalcodepostalcodepostalInfo;
                }
            }
        }

        /// <summary>
        /// The FirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("9cc3bb7f-c2cf-455b-b2e1-1d15b4ddbaba")]
        public partial class FirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fromthiswebsiteInfo;
            RepoItemInfo _coleccionbiologiauvgmozillafirefoxInfo;

            /// <summary>
            /// Creates a new Firefox  folder.
            /// </summary>
            public FirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Firefox", "/form[@title='']", parentFolder, 30000, null, true, "9cc3bb7f-c2cf-455b-b2e1-1d15b4ddbaba", "")
            {
                _fromthiswebsiteInfo = new RepoItemInfo(this, "FromThisWebsite", "?/?/list[@accessiblerole='List']/listitem[@accessiblename>'andrea.elias166@gmail.com']/?/?/text[@accessiblename='From this website']", 30000, null, "d996710a-5469-42a1-8230-1ac693079bdd");
                _coleccionbiologiauvgmozillafirefoxInfo = new RepoItemInfo(this, "ColeccionBiologiaUVGMozillaFirefox", "?/?/listitem[@accessiblename>'Coleccion Biologia UVG - Mozilla']", 30000, null, "840bb828-e141-4e58-a335-cdbfd0a06c66");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9cc3bb7f-c2cf-455b-b2e1-1d15b4ddbaba")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9cc3bb7f-c2cf-455b-b2e1-1d15b4ddbaba")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FromThisWebsite item.
            /// </summary>
            [RepositoryItem("d996710a-5469-42a1-8230-1ac693079bdd")]
            public virtual Ranorex.Text FromThisWebsite
            {
                get
                {
                    return _fromthiswebsiteInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FromThisWebsite item info.
            /// </summary>
            [RepositoryItemInfo("d996710a-5469-42a1-8230-1ac693079bdd")]
            public virtual RepoItemInfo FromThisWebsiteInfo
            {
                get
                {
                    return _fromthiswebsiteInfo;
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVGMozillaFirefox item.
            /// </summary>
            [RepositoryItem("840bb828-e141-4e58-a335-cdbfd0a06c66")]
            public virtual Ranorex.ListItem ColeccionBiologiaUVGMozillaFirefox
            {
                get
                {
                    return _coleccionbiologiauvgmozillafirefoxInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVGMozillaFirefox item info.
            /// </summary>
            [RepositoryItemInfo("840bb828-e141-4e58-a335-cdbfd0a06c66")]
            public virtual RepoItemInfo ColeccionBiologiaUVGMozillaFirefoxInfo
            {
                get
                {
                    return _coleccionbiologiauvgmozillafirefoxInfo;
                }
            }
        }

        /// <summary>
        /// The Form21WhatsAppMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("161da3d2-941e-402a-aeca-10b83e17b8b0")]
        public partial class Form21WhatsAppMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _coleccionbiologiauvgInfo;

            /// <summary>
            /// Creates a new Form21WhatsAppMozillaFirefox  folder.
            /// </summary>
            public Form21WhatsAppMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Form21WhatsAppMozillaFirefox", "/form[@title>'(21) WhatsApp - Mozilla F']", parentFolder, 30000, null, true, "161da3d2-941e-402a-aeca-10b83e17b8b0", "")
            {
                _coleccionbiologiauvgInfo = new RepoItemInfo(this, "ColeccionBiologiaUVG", "toolbar[@accessiblename='Browser tabs']/?/?/tabpage[@accessiblerole='PageTab' and @title='Coleccion Biologia UVG' and @index='5']/text[@accessiblename='Coleccion Biologia UVG']", 30000, null, "2a908b37-d055-443a-b93b-091e0f0a62af");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("161da3d2-941e-402a-aeca-10b83e17b8b0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("161da3d2-941e-402a-aeca-10b83e17b8b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG item.
            /// </summary>
            [RepositoryItem("2a908b37-d055-443a-b93b-091e0f0a62af")]
            public virtual Ranorex.Text ColeccionBiologiaUVG
            {
                get
                {
                    return _coleccionbiologiauvgInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ColeccionBiologiaUVG item info.
            /// </summary>
            [RepositoryItemInfo("2a908b37-d055-443a-b93b-091e0f0a62af")]
            public virtual RepoItemInfo ColeccionBiologiaUVGInfo
            {
                get
                {
                    return _coleccionbiologiauvgInfo;
                }
            }
        }

        /// <summary>
        /// The LiteappsMcafeeComAppFolder folder.
        /// </summary>
        [RepositoryFolder("e825de0e-7071-46c9-9632-c746bfca97b7")]
        public partial class LiteappsMcafeeComAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mcafeewebprotectionInfo;
            RepoItemInfo _hiliteInfo;

            /// <summary>
            /// Creates a new LiteappsMcafeeCom  folder.
            /// </summary>
            public LiteappsMcafeeComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("LiteappsMcafeeCom", "/dom[@domain='liteapps.mcafee.com']", parentFolder, 30000, null, false, "e825de0e-7071-46c9-9632-c746bfca97b7", "")
            {
                _mcafeewebprotectionInfo = new RepoItemInfo(this, "McAfeeWebProtection", ".//h1[#'Results_WebProt_title']/span[@innertext='McAfee Web Protection']", 30000, null, "edbec3df-703c-4395-b8e3-75e28eced7ec");
                _hiliteInfo = new RepoItemInfo(this, "Hilite", ".//div[#'Results_OnlinePrivacy']/div[1]/div[2]", 30000, null, "ffdcec17-6aa4-4f7a-a354-8d9341b7b2a0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e825de0e-7071-46c9-9632-c746bfca97b7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e825de0e-7071-46c9-9632-c746bfca97b7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The McAfeeWebProtection item.
            /// </summary>
            [RepositoryItem("edbec3df-703c-4395-b8e3-75e28eced7ec")]
            public virtual Ranorex.SpanTag McAfeeWebProtection
            {
                get
                {
                    return _mcafeewebprotectionInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The McAfeeWebProtection item info.
            /// </summary>
            [RepositoryItemInfo("edbec3df-703c-4395-b8e3-75e28eced7ec")]
            public virtual RepoItemInfo McAfeeWebProtectionInfo
            {
                get
                {
                    return _mcafeewebprotectionInfo;
                }
            }

            /// <summary>
            /// The Hilite item.
            /// </summary>
            [RepositoryItem("ffdcec17-6aa4-4f7a-a354-8d9341b7b2a0")]
            public virtual Ranorex.DivTag Hilite
            {
                get
                {
                    return _hiliteInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Hilite item info.
            /// </summary>
            [RepositoryItemInfo("ffdcec17-6aa4-4f7a-a354-8d9341b7b2a0")]
            public virtual RepoItemInfo HiliteInfo
            {
                get
                {
                    return _hiliteInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
