///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Colecciones_Biologia
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording4 recording.
    /// </summary>
    [TestModule("6ef5cfaf-fb2b-4e84-9475-8118d95c78b4", ModuleType.Recording, 1)]
    public partial class Recording4 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Colecciones_BiologiaRepository repository.
        /// </summary>
        public static Colecciones_BiologiaRepository repo = Colecciones_BiologiaRepository.Instance;

        static Recording4 instance = new Recording4();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording4()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording4 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG.AcercaDeNosotros' at 72;15.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG.AcercaDeNosotrosInfo, new RecordItemIndex(0));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG.AcercaDeNosotros.Click("72;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;73.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(1));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;73");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;108.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(2));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;108");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Next') on item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next'.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NextInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NextInfo, "Text", "Next");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next' at 142;405.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NextInfo, new RecordItemIndex(4));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next.Click("142;405");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next' at 142;405.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NextInfo, new RecordItemIndex(5));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next.MoveTo("142;405");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next' at 142;405.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NextInfo, new RecordItemIndex(6));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Next.MoveTo("142;405");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;252.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(7));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;252");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;378.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(8));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;378");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1911;375.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(9));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1911;375");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;427.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(10));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;427");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1914;434.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(11));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1914;434");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;534.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(12));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;534");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1919;534.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(13));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1919;534");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'ColeccionBiologiaUVGMozillaFirefox.None' at 1918;180.", repo.ColeccionBiologiaUVGMozillaFirefox.NoneInfo, new RecordItemIndex(14));
            repo.ColeccionBiologiaUVGMozillaFirefox.None.MoveTo("1918;180");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
