///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Colecciones_Biologia
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The searchFuncionality recording.
    /// </summary>
    [TestModule("c6fb7ea6-f51e-4560-bae4-3052014b3596", ModuleType.Recording, 1)]
    public partial class searchFuncionality : ITestModule
    {
        /// <summary>
        /// Holds an instance of the Colecciones_BiologiaRepository repository.
        /// </summary>
        public static Colecciones_BiologiaRepository repo = Colecciones_BiologiaRepository.Instance;

        static searchFuncionality instance = new searchFuncionality();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public searchFuncionality()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static searchFuncionality Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Firefox.ColeccionBiologiaUVGMozillaFirefox' at 30;100.", repo.Firefox.ColeccionBiologiaUVGMozillaFirefoxInfo, new RecordItemIndex(0));
            repo.Firefox.ColeccionBiologiaUVGMozillaFirefox.Click("30;100");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG2' at 148;8.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG2Info, new RecordItemIndex(1));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG2.Click("148;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Buscar' at 385;17.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.BuscarInfo, new RecordItemIndex(2));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Buscar.Click("385;17");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ahsnf' with focus on 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Buscar'.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.BuscarInfo, new RecordItemIndex(3));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.Buscar.PressKeys("ahsnf");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None1'.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None1Info, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None1Info, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleState='None') on item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None1'.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None1Info, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None1Info, "AccessibleState", "None");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None' at 638;535.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NoneInfo, new RecordItemIndex(6));
            repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None.Click("638;535");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None'.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NoneInfo, new RecordItemIndex(7));
            Validate.AttributeEqual(repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NoneInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleState='None') on item 'ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.None'.", repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NoneInfo, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.ColeccionBiologiaUVGMozillaFirefox.ColeccionBiologiaUVG1.NoneInfo, "AccessibleState", "None");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
