export const SUGGESTIONS_FOUNDED = "SUGGESTIONS_FOUNDED";
export const SUGGESTIONS_SEARCHING = "SUGGESTIONS_SEARCHING";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
export const SEARCH_RESULTS_FOUNDED = "SEARCH_RESULTS_FOUNDED";
